// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SongselectTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void songselect() {
    driver.Navigate().GoToUrl("https://www.youtube.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1158, 969);
    driver.FindElement(By.Name("search_query")).Click();
    driver.FindElement(By.Name("search_query")).SendKeys("Progressive Psytrance Mix - Dream Frequency");
    driver.FindElement(By.CssSelector("#search-icon-legacy > .style-scope:nth-child(1)")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".ytd-item-section-renderer:nth-child(1) > #dismissable #video-title > .style-scope:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".ytd-item-section-renderer:nth-child(1) > #dismissable #video-title > .style-scope:nth-child(2)")).Click();
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".ytd-compact-autoplay-renderer > #dismissable #img"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
  }
}
